name: Upload when release and Update Pages
on:
  push:
    branches:
      - main
jobs:
  build-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          packages: >
            l3build latex latex-bin luatex latex-bin-dev parskip kvoptions ltxcmds etoolbox collection-latexextra scheme-basic hyperref ebgaramond

      - name: Build examples
        run: pdflatex -interaction=nonstopmode -halt-on-error resume.tex

      - name: Create index.html
        run: mkdir public && echo "<!DOCTYPE html><html lang='fr'><head><meta charset='UTF-8'><link rel="icon" type="image/x-icon" href="https://cdn-icons-png.flaticon.com/512/5766/5766858.png"><script type='text/javascript'>window.location.href='./resume.pdf'</script><title>Redirection vers le PDF</title></head></html>" > public/index.html

      - name: Move PDFs
        run: mv resume.pdf public

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          personal_token: ${{ secrets.CICD_TOKEN }}
          publish_dir: public
          allow_empty_commit: true
          force_orphan: true
          enable_jekyll: true
